/* Generated By:JavaCC: Do not edit this line. LPGeneratorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LPGeneratorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int ELSE = 4;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int FORALL = 6;
  /** RegularExpression Id. */
  int EXISTS = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int FUN = 10;
  /** RegularExpression Id. */
  int MINIMIZE = 11;
  /** RegularExpression Id. */
  int MAXIMIZE = 12;
  /** RegularExpression Id. */
  int LIBRARY = 13;
  /** RegularExpression Id. */
  int VARIABLE = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int DEF = 16;
  /** RegularExpression Id. */
  int SUBJECT = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int IMPORT = 19;
  /** RegularExpression Id. */
  int INTEGER = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"forall\"",
    "\"exists\"",
    "\"in\"",
    "\"for\"",
    "\"fun\"",
    "\"minimize\"",
    "\"maximize\"",
    "\"library\"",
    "<VARIABLE>",
    "\"number\"",
    "\"def\"",
    "\"subject\"",
    "\"var\"",
    "\"import\"",
    "<INTEGER>",
    "<DOUBLE>",
    "<IDENTIFIER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"?\"",
    "\"->\"",
    "\"||\"",
    "\"&&\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"//\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"[\"",
    "\"]\"",
  };

}
